### ISSUE TITLE
Recent change in duration of a year in `lubridate` breaks one test

### ISSUE THREAD

**Issue by vspinu** [mps9506/tbrf#12]
The average length of a year duration is now 365.25 insteadd of 365. This is for consistency with all other places and conceptual reasons. 

The failure is in this [revdep check](https://github.com/tidyverse/lubridate/blob/ce646878ac6eedeac909737fc85238431e5df920/revdep/problems.md#tbrf). I believe it has to do with [this line](https://github.com/mps9506/tbrf/blob/a782bfd5381c813256a4e08f552123526f5fdf32/R/tbr_sum.R#L65) where duration is used extensively. 

I didn't sink into the logic but it looks to me that with either definition of average yearly duration it won't be correct in all situation. Probably using periods or better intervals might be a better approach. 

Sorry for the trouble.

**Comment by mps9506** [comment]
@vspinu thank you for the notification. I tested pull request #13 against the current development version of `lubridate` and the problem is resolved. Your suggestions were correct.
